FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Upgrade pip (important)
RUN python -m pip install --upgrade pip

# Install dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

# Create required folders
RUN mkdir -p logs reports

# Run the pentest framework
CMD ["python", "core/runner.py"]
